### ISSUE TITLE
WITHSCORES in ZRANGE causes error "can't convert Symbol into Integer"

### ISSUE THREAD

**Issue by diafygi** [alexmchale/try.redis#10]
Example

```
> ZADD key1 12 "user1"
true
> ZRANGE key1 0 -1
["user1"]
> ZRANGE key1 0 -1 WITHSCORES
can't convert Symbol into Integer
```

Expected behavior

```
> ZRANGE key1 0 -1 WITHSCORES
[("user1", 12.0)]
```

**Comment by boyaq** [comment]
The error happens only when try it on http://try.redis-db.com. It's working normal on my server.

**Comment by kprzywara** [comment]
This works for me:
$redis.zrange("key", 0, -1, :with_scores => true)

**Comment by badboy** [comment]
@kprzywara Just that it is totally unrelated and this bug is superold and already fixed.

**Comment by kprzywara** [comment]
I think its totally related because I ran into similar error myself yesterday and thats how I found this post. You cannot use that syntax as posted originally which is also how its documented on redis website. 

Here is with the latest version of my redis output with wrong parameter:
2.1.2 :091 > $redis.zrange("redis_q3", 0, -1, WITHSCORES)
NameError: uninitialized constant WITHSCORES

If you use :with_scores => true, then it works fine..

**Comment by badboy** [comment]
But you're mixing default Redis syntax (as used by try.redis and redis-cli) and your library code ;)

**Comment by kprzywara** [comment]
lol - i don't know.. I'm new to redis so maybe I'm mixing stuff but maybe someone with my thinking will find that useful cause it helped me when I finally found the answer :)

**Comment by kprzywara** [comment]
ah I see what you mean.. lol.. i didn't even realize that Im posting this on a different library.. sorry
